### PR TITLE
 fix error in pleat circular; fix and format all inx files 

### PR DESCRIPTION
**Pull request by vmario89**
this commit fixes to stop several errors in cli. since inkscape 1.0 the inx descriptors massively changed. you used a lot of old tags and attributes.

### CODE REVIEW

**Comment by evbernardes** [comment]
Hey there! Thanks for being interested in this little extension! Guess I wasn't expecting someone else to find it useful :)

I'll study the merge when I get some time, just some questions:

1. I see "FabLab Chemnitz Boxes/Papercraft" was added as the menu option in one of the inx files, I imagine it was supposed to be from some other fork? I also noticed "<id>fablabchemnitz.de.origami_patterns.kresling_full</id>" as the id of some files.

2. There's a little typo in the file "origa_boxes_masu_traditional.inx" since it was renamed to "origa_oxes_masu_traditional.inx"

3. The files "origa_bendy_straw.inx" and "origa_kresling.inx" were created, what are the differences since both "origa_cylindrical_bendy_straw.inx" and "origa_cylindrical_kresling.inx" still exist?

Do you mind sharing what kinds of old tags and attributes I should be avoiding? I haven't had a lot of time recently but I plan on taking some time to finish some ideas after I'm done with my PhD thesis! (and maybe implementing other patterns, if there are any patterns that you'd like to see implemented, please tell me!)

Thanks again for the interest!

**Comment by vmario89** [comment]
hi.thanks for looking into. indeed i messed up some stuff. i fixed that now.

i did a lot of adjustments in inx. At first i formatted all cleanly using https://www.freeformatter.com/xml-formatter.html

i replaced the following stuff to be convenient:

- `<_param name="help"   type="description" xml:space="preserve">------------------------------------------------------------</_param>` should use <label> now
-  params of type optiongroup do not have appearance=minimal. you can use "combo" and you MUST add the appearance
- `<command reldir="extensions" interpreter="python"> `is now `<command location="inx" interpreter="python">`
there are a lot more. please feel free to have a look at https://inkscape.gitlab.io/extensions/documentation/authors/inx-overview.html and especially https://wiki.inkscape.org/wiki/index.php?title=Extensions:_INX_widgets_and_parameters&oldid=119643 (note: the recent version of that wiki page does not contain that info anymore. this is a bit stupid)

**Comment by evbernardes** [comment]
Hey there @vmario89! Thanks for answering me. I'll look into it a bit better when I have some time.

If that's okay with you, I'd really appreciate if you just changed the problematic lines without using the automatic formatter, removing the comments or changing the tabs for spaces.

While I plan on doing all that too eventually, this makes it very hard for me to follow the diffs of your commit, so I'd prefer if the formatting and non essential changes were left for a different commit (sorry about that!)

If you don't have time for that, no problem, I'll do it all myself (will just take some more time since I've been quite busy lately).

(In the meantime, I added a .gitignore file in order not to add the __pycache__ folder to the repo, I had forgotten about that before!)

**Comment by vmario89** [comment]
hi. sorry same situation for me. i dont have the time to revert back the changes for each single step :-(

**Comment by evbernardes** [comment]
> hi. sorry same situation for me. i dont have the time to revert back the changes for each single step :-(

Hey there again, @vmario89! Managed to find some time to review your suggestions. Thanks a lot for them!

I changed:

1. The tabs to spaces as the formatter had done
2. Remove most comments on the inx files, but left them on the **template** files
3. Changed `title` to `options` in most main tabs
4. Removed the translatable tags
5. Changed appearance from `"minimal"` to `"combo"` in `optiongroup` as you suggested
6. changed `reldir="extensions"` to `location="inx"`

I think this is all! Sorry for not accepting directly your pull request and redoing it all manually, but I found it easier to do it like this from my side.

Tell me if everything is ok now so I can close it! :)

EDIT.: I also took the opportunity to do some changes I have wanted to do for a while, like changing those `----------` to `<spacer/>`

**Comment by vmario89** [comment]
looks good so far! if you want to do it perfectly, you can also validate the inx files by running

`xmllint --noout --relaxng ../inkscape.extension.rng *.inx` - that file can be obtained by https://gitlab.com/inkscape/extensions/-/blob/master/inkscape.extension.rng

**Comment by evbernardes** [comment]
@vmario89 oh that's interesting, I'll definitely check that out! Thanks for the tip :)

Btw, as a last change to the inx files, studying the new widgets and parameters I thought of maybe using `appearance="colorbutton"` for the color selectors. What do you think of that?

**Comment by vmario89** [comment]
hey. changing to colorbutton might cleanup the interface, as we do not really need the transparancies; except for origami simulator maybe^^

**Pull request closed without merging**
